{"info": {"author": "Jimin Huang", "author_email": "huangjimin@whu.edu.cn", "bugtrack_url": null, "classifiers": [], "description": "", "description_content_type": "", "docs_url": null, "download_url": "", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "https://gitee.com/QianFuFinancial/chance-exception-capturer.git", "keywords": "", "license": "MIT", "maintainer": "", "maintainer_email": "", "name": "chance-exception-capturer", "package_url": "https://pypi.org/project/chance-exception-capturer/", "platform": "", "project_url": "https://pypi.org/project/chance-exception-capturer/", "project_urls": {"Homepage": "https://gitee.com/QianFuFinancial/chance-exception-capturer.git"}, "release_url": "https://pypi.org/project/chance-exception-capturer/0.0.2/", "requires_dist": null, "requires_python": "", "summary": "The exception capturer for chancefocus", "version": "0.0.2", "yanked": false, "html_description": null}, "last_serial": 4537204, "releases": {"0.0.1": [{"comment_text": "", "digests": {"md5": "15caa4032fac333c5e445109626ffcaf", "sha256": "3c10f86c2a955c80133b3331bf9c3cd44a9252bc2d2a228f72330f0e8d375b3c"}, "downloads": -1, "filename": "chance-exception-capturer-0.0.1.tar.gz", "has_sig": false, "md5_digest": "15caa4032fac333c5e445109626ffcaf", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1893, "upload_time": "2018-08-03T06:48:38", "upload_time_iso_8601": "2018-08-03T06:48:38.524114Z", "url": "https://files.pythonhosted.org/packages/d1/b8/d48a7e8a18ab7fc86a5302bc55ef4926aa421602f2d7f84ddb299ce6e700/chance-exception-capturer-0.0.1.tar.gz", "yanked": false}], "0.0.2": [{"comment_text": "", "digests": {"md5": "54f6dac6bc479c760d4ce7ae67ce8e2c", "sha256": "005ef08344c895188a3f05b60694c3236280b944b6aa187e5298078082c8d7fe"}, "downloads": -1, "filename": "chance-exception-capturer-0.0.2.tar.gz", "has_sig": false, "md5_digest": "54f6dac6bc479c760d4ce7ae67ce8e2c", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1899, "upload_time": "2018-11-28T06:27:26", "upload_time_iso_8601": "2018-11-28T06:27:26.917234Z", "url": "https://files.pythonhosted.org/packages/45/9a/f63dc0a1629b287bdd3a643b3d6c82b139a109e3d24f3f9e3820fec3de83/chance-exception-capturer-0.0.2.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "54f6dac6bc479c760d4ce7ae67ce8e2c", "sha256": "005ef08344c895188a3f05b60694c3236280b944b6aa187e5298078082c8d7fe"}, "downloads": -1, "filename": "chance-exception-capturer-0.0.2.tar.gz", "has_sig": false, "md5_digest": "54f6dac6bc479c760d4ce7ae67ce8e2c", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1899, "upload_time": "2018-11-28T06:27:26", "upload_time_iso_8601": "2018-11-28T06:27:26.917234Z", "url": "https://files.pythonhosted.org/packages/45/9a/f63dc0a1629b287bdd3a643b3d6c82b139a109e3d24f3f9e3820fec3de83/chance-exception-capturer-0.0.2.tar.gz", "yanked": false}], "timestamp": "Thu May  7 22:34:30 2020"}