{"info": {"author": "Shyam Satyaprasad", "author_email": "shyam.ns114@gmail.com", "bugtrack_url": null, "classifiers": [], "description": "", "description_content_type": "", "docs_url": null, "download_url": "", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "http://github.com/im-shyam/django_error_assist", "keywords": "", "license": "MIT", "maintainer": "", "maintainer_email": "", "name": "django-error-assist", "package_url": "https://pypi.org/project/django-error-assist/", "platform": "", "project_url": "https://pypi.org/project/django-error-assist/", "project_urls": {"Homepage": "http://github.com/im-shyam/django_error_assist"}, "release_url": "https://pypi.org/project/django-error-assist/0.1.5/", "requires_dist": null, "requires_python": "", "summary": "Allows user to search the django errors on google/stackoverflow with a link.", "version": "0.1.5", "yanked": false, "html_description": null}, "last_serial": 3890158, "releases": {"0.1.4": [{"comment_text": "", "digests": {"md5": "59945ddf1ff96ec1dc409a191bbe17fc", "sha256": "e02de2e67ef1bed4966d23c259d62f6bbe6a89fe39f118f341edd661a380b0fe"}, "downloads": -1, "filename": "django_error_assist-0.1.4.tar.gz", "has_sig": false, "md5_digest": "59945ddf1ff96ec1dc409a191bbe17fc", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2167, "upload_time": "2017-10-12T13:28:49", "upload_time_iso_8601": "2017-10-12T13:28:49.512132Z", "url": "https://files.pythonhosted.org/packages/92/d1/39e29faea385a2db620b20f186a20964e61cd7809cb5d8560ba5bad1c5cb/django_error_assist-0.1.4.tar.gz", "yanked": false}], "0.1.5": [{"comment_text": "", "digests": {"md5": "f17b12b59ea409b406de6dcee351c3d4", "sha256": "46e4e2fdf936432a9d0ee3572e0bd5fad87be6addab1dd802da7c80b4b4e74a6"}, "downloads": -1, "filename": "django_error_assist-0.1.5.tar.gz", "has_sig": false, "md5_digest": "f17b12b59ea409b406de6dcee351c3d4", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2654, "upload_time": "2018-05-23T06:00:57", "upload_time_iso_8601": "2018-05-23T06:00:57.903689Z", "url": "https://files.pythonhosted.org/packages/4c/b5/9fdabc82e285ff455043e36da520343b5f092d68ee039ee0927021fc8350/django_error_assist-0.1.5.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "f17b12b59ea409b406de6dcee351c3d4", "sha256": "46e4e2fdf936432a9d0ee3572e0bd5fad87be6addab1dd802da7c80b4b4e74a6"}, "downloads": -1, "filename": "django_error_assist-0.1.5.tar.gz", "has_sig": false, "md5_digest": "f17b12b59ea409b406de6dcee351c3d4", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2654, "upload_time": "2018-05-23T06:00:57", "upload_time_iso_8601": "2018-05-23T06:00:57.903689Z", "url": "https://files.pythonhosted.org/packages/4c/b5/9fdabc82e285ff455043e36da520343b5f092d68ee039ee0927021fc8350/django_error_assist-0.1.5.tar.gz", "yanked": false}], "timestamp": "Fri May  8 00:36:19 2020"}