{"info": {"author": "Dieter Maurer", "author_email": "dieter@handshake.de", "bugtrack_url": null, "classifiers": ["Development Status :: 5 - Production/Stable", "Framework :: Zope2", "Intended Audience :: Developers", "License :: OSI Approved :: Zope Public License", "Operating System :: OS Independent", "Programming Language :: Python", "Topic :: Utilities"], "description": "This package patches the web application server Zope to work around\nhttps://bugs.launchpad.net/zope2/+bug/740831.\n\nThe bug causes Zope to deliver wrong responses after a request using\n``Response.write`` has suffered a ``ConflictError``. The patch\nprevents Zope from retrying such requests and logs an error message when it\ntries. The bug effect is thus limited to a single request.\n\nNote that even with this patch Zope does not behave fully correctly: in\ncase of a ``ConflictError``, it may\ndeliver a (maybe partial) response even though the transaction has\nbeen aborted. The client does not get feedback for the transaction rollback.\nThe only indication is the log record written.\n\n``Response.write`` is inherently unsafe in the face of ``ConflictError``.\nThe only reliable fix is not to use it at all.\n\n\nThe (monkey) patch gets installed when this package is imported.", "description_content_type": null, "docs_url": null, "download_url": "UNKNOWN", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "http://pypi.python.org/pypi/dm.zopepatches.fix_responsewrite_conflict", "keywords": "patch wrong response Zope2", "license": "BSD", "maintainer": null, "maintainer_email": null, "name": "dm.zopepatches.fix_responsewrite_conflict", "package_url": "https://pypi.org/project/dm.zopepatches.fix_responsewrite_conflict/", "platform": "UNKNOWN", "project_url": "https://pypi.org/project/dm.zopepatches.fix_responsewrite_conflict/", "project_urls": {"Download": "UNKNOWN", "Homepage": "http://pypi.python.org/pypi/dm.zopepatches.fix_responsewrite_conflict"}, "release_url": "https://pypi.org/project/dm.zopepatches.fix_responsewrite_conflict/1.0/", "requires_dist": null, "requires_python": null, "summary": "Zope[2] patch to alleviate the effect of https://bugs.launchpad.net/zope2/+bug/740831.", "version": "1.0", "yanked": false, "html_description": "<div class=\"project-description\">\n            <p>This package patches the web application server Zope to work around\n<a href=\"https://bugs.launchpad.net/zope2/+bug/740831\" rel=\"nofollow\">https://bugs.launchpad.net/zope2/+bug/740831</a>.</p>\n<p>The bug causes Zope to deliver wrong responses after a request using\n<tt>Response.write</tt> has suffered a <tt>ConflictError</tt>. The patch\nprevents Zope from retrying such requests and logs an error message when it\ntries. The bug effect is thus limited to a single request.</p>\n<p>Note that even with this patch Zope does not behave fully correctly: in\ncase of a <tt>ConflictError</tt>, it may\ndeliver a (maybe partial) response even though the transaction has\nbeen aborted. The client does not get feedback for the transaction rollback.\nThe only indication is the log record written.</p>\n<p><tt>Response.write</tt> is inherently unsafe in the face of <tt>ConflictError</tt>.\nThe only reliable fix is not to use it at all.</p>\n<p>The (monkey) patch gets installed when this package is imported.</p>\n\n          </div>"}, "last_serial": 791271, "releases": {"1.0": [{"comment_text": "", "digests": {"md5": "4eea4c8d67063140fe0181082b54feec", "sha256": "089772d070e4a413201b433f061bfd5097185ae66133ff76f720354db4601a17"}, "downloads": -1, "filename": "dm.zopepatches.fix_responsewrite_conflict-1.0.tar.gz", "has_sig": false, "md5_digest": "4eea4c8d67063140fe0181082b54feec", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2612, "upload_time": "2011-03-23T12:18:38", "upload_time_iso_8601": "2011-03-23T12:18:38.485331Z", "url": "https://files.pythonhosted.org/packages/86/cb/0a397e44ccc370e6727ab16178ff0d92f274f3906795c2ca1a583b13c9fd/dm.zopepatches.fix_responsewrite_conflict-1.0.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "4eea4c8d67063140fe0181082b54feec", "sha256": "089772d070e4a413201b433f061bfd5097185ae66133ff76f720354db4601a17"}, "downloads": -1, "filename": "dm.zopepatches.fix_responsewrite_conflict-1.0.tar.gz", "has_sig": false, "md5_digest": "4eea4c8d67063140fe0181082b54feec", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2612, "upload_time": "2011-03-23T12:18:38", "upload_time_iso_8601": "2011-03-23T12:18:38.485331Z", "url": "https://files.pythonhosted.org/packages/86/cb/0a397e44ccc370e6727ab16178ff0d92f274f3906795c2ca1a583b13c9fd/dm.zopepatches.fix_responsewrite_conflict-1.0.tar.gz", "yanked": false}], "timestamp": "Fri May  8 00:51:11 2020"}