{"info": {"author": "Tom Carroll", "author_email": "actuator@pobox.com", "bugtrack_url": null, "classifiers": [], "description": "errator\r\n=======\r\n\r\nProvide human-readable error narration of exception tracebacks with ``errator``.\r\n\r\n#. `What's new in 0.3 <#what-s-new-in-0-3>`__\r\n#. `Intro <#intro>`__\r\n#. `How it works <#how-it-works>`__\r\n#. `Requirements <#requirements>`__\r\n#. `Installing <#installing>`__\r\n#. `Quick Start <#quick-start>`__\r\n#. `Building from source <#building-from-source>`__\r\n\r\nWhat's new in 0.3\r\n-----------------\r\nThis is largely a performance release for ``errator``, as it implements the more costly part of the narration process in a `Cython <http://cython.org/>`__ extension. Additionally, there has been a change in the way verbose narrations are performed, as the original approach entailed a lot of overhead even if verbose narrations weren't required.\r\n\r\n- ``errator`` now consists of a Python file and a  Python extension module (built from a Cython source), which improves runtime performance\r\n\r\n- The 'verbose' keyword argument has been removed from the ``get_narration()`` function, and has been added to the ``set_narration_options()`` and ``set_default_options()`` functions. Now getting verbose narrations is a matter of setting the option either as a default or on a per-thread basis, hence this option must be set `before` collecting narrations.\r\n\r\n- Previously, detailed exception information (file name, line number) was always collected in case a user wanted to fetch verbose narration information with ``get_narration()``. However, this proved to be a big performance hit, and now this information is `only` collected if the 'verbose' option has been set with ``set_narration_options()`` or ``set_default_options()`` function `before` the exception occurs.\r\n\r\nWhat's new in 0.2.1\r\n-------------------\r\n\r\nThis patch release addresses certain performance issues:\r\n\r\n- Patched a bug that caused too many object creations to occur\r\n\r\n- Removed some redundant resetting of state in narration fragment objects\r\n\r\n- Added caching of filenames for function objects so that lookups aren't always required\r\n\r\n- Sped up the resetting process\r\n\r\n\r\nWhat's new in 0.2\r\n-----------------\r\n\r\n- The ``get_narration()`` now has a new keyword argument, \"verbose\" (default False), that when True returns expanded narration information that includes the line number, function, and file name of the point in the stack trace that the narration applies to.\r\n\r\n- To provide a more tidy display of stack information, ``errator`` now has analogs of the functions from the standard ``traceback`` module that filter out ``errator``-based calls from the call stack, leaving only application calls in the display of stack traces.\r\n\r\n- Narration output formatting has been modified slightly.\r\n\r\nIntro\r\n-----\r\n\r\n``errator`` came as an idea on the back of trying to figure out what the semantics of an exception traceback are in non-trivial pieces of code.\r\n\r\nWhen an exception occurs deep inside a call stack within some generic utility function that is used in numerous contexts, reading the traceback is often not helpful in determining the source of the problem. Data values aren't obvious, and the initial starting conditions of the error can't easily been seen.\r\n\r\nLogging is a step in the right direction, but in general outputs too much information; often, there is lots of info regarding error-free processing in the log, making it hard to find the right log output that is associated with the error.\r\n\r\n``errator`` is something of a marriage between logging and tracebacks: plain text messages that are associated directly with the call trail that led to an exception. ``errator`` works by providing tools that let you state intent of code in text, but only captures that text when an exception bubbles up the stack. You can then acquire this \"error narration\" and display it to your user in the most appropriate fashion.\r\n\r\nHow it works\r\n------------\r\n\r\n``errator`` uses decorators and context managers to maintain a stack of \"narration fragments\" behind the scenes. When code executes without exceptions, these fragments are created and thrown away as narrated code executes and returns. However, when an exception is raised, the narration fragments are retained and their content can be retrieved. Fragments can be automatically discarded (pruned) when an exception doesn't propagate any further up the stack, or can be discarded under user control, allowing more control over the content of \"narration\" provided for the exception.\r\n\r\n``errator`` is thread-safe, allowing you to capture separate error narrations for independent threads of control through the same code.\r\n\r\nRequirements\r\n------------\r\n\r\n``errator`` doesn't have any runtime external dependencies, and is compatible with Python 2.7 and 3.x. If you wish to build from source, you'll need to install Cython to build the extension module, and have a C compiler and the required Python header files.\r\n\r\nInstalling\r\n----------\r\n\r\nAs of 0.3, ``errator`` is comprised of a Python module and an extension wrapper. You can install it with ``pip install errator``, or you can clone the Git project and build from source (more on this below).\r\n\r\nQuick Start\r\n-----------\r\n\r\nThe next section discusses ``errator`` with functions, but you can also use the decorators described with methods too.\r\n\r\n**Basic Use**\r\n\r\nStart by importing ``errator`` into the module that you want to narrate:\r\n\r\n.. code:: python\r\n\r\n    from errator import *\r\n\r\nNow, suppose you have a utility function that performs some specialized string formatting, but it is possible to pass in arguments that cause a exception to be raised. Your function is called all over the place for a variety of different reasons, often very deep down the call stack where it isn't obvious what the original functional intent was, or where the source of bad arguments may have been.\r\n\r\nTo start building the narration to your function's execution, you can use the ``narrate()`` decorator to associate a bit of text with your utility function in order to provide easily understandable explanations about what's going on:\r\n\r\n.. code:: python\r\n\r\n    @narrate(\"I'm trying to format a string\")\r\n    def special_formatter(fmt_string, **kwargs):\r\n        # magic format code that sometimes raises an exception\r\n\r\nThe ``narrate()`` decorator knows to look for exceptions and doesn't impede their propagation, but captures that bit of text in an internal stack when an exception occurs. So if you write:\r\n\r\n.. code:: python\r\n\r\n    try:\r\n        s = special_formatter(fmt, **args)\r\n    exception Exception:\r\n        the_tale = get_narration()\r\n\r\n...and ``special_formatter()`` raises an exception, the exception will still bubble up the stack, but ``get_narration()`` will return a list of strings for all the ``narrate()``-decorated functions down to the exception. If no exception is raised, there are no strings to fetch (unless you want there to be strings, but we'll get to that).\r\n\r\n**Getting more information**\r\n\r\nMaybe you'd like some insight as to the value of the arguments passed when an exception is raised, so you can better tell what's causing it. Instead of a string, you can supply the ``narrate()`` decorator with a callable that returns a string and that has the same signature as the function being decorated. This callable will `only be invoked if the decorated function raises an exception`, and gets invoked with the same arguments as the function:\r\n\r\n.. code:: python\r\n\r\n    @narrate(lambda fs, **kw: \"I'm trying to format a string with '%s' and args '%s'\" % (fs, str(kw)))\r\n    def special_formatter(fmt_string, **kwargs):\r\n        # magic format code that sometimes raises an exception\r\n\r\nThe lambda passed to narrate() will only be called when ``special_formatter()`` raises an exception, otherwise it will go un-executed.\r\n\r\n**Finer details with contexts**\r\n\r\nNow, perhaps ``special_formatter()`` is a rather long function, and you'd like to be able to narrate it's operation in more detail to get better narrations when things go wrong. You can use the ``narrate_cm()`` context manager to create a narration fragment for a block of code. If everything goes well in the block, then the fragment is discarded, but the fragment will be retained if an exception occurs:\r\n\r\n.. code:: python\r\n\r\n    def special_formatter(fmt_string, **kwargs):\r\n        for format_token in parse_format(fmt_string):\r\n            if format_token.type == float:\r\n                with narrate_cm(\"I started processing a float format\"):\r\n                    # do magic stuff for floats...\r\n            elif format_token.type == int:\r\n                with narrate_cm(\"I started processing an int format\"):\r\n                    # do magic stuff for ints...\r\n\r\nNarration fragments added with ``narrate_cm()`` are treated just like those created by the function decorator-- they are added to the stack, and silently removed if the context manager's code block exits normally. But exceptions raised in the context block are retained as the exception propagates back through the stack.\r\n\r\nLike ``narrate()``, ``narrate\\_cm()`` allows you to supply a callable instead of\r\na string:\r\n\r\n.. code:: python\r\n\r\n    with narrate_cm(lambda x: \"I started processing an int with format %s\" % x, format_token.format):\r\n        # format code\r\n\r\n...and again, this callable will only be invoked if an exception is raised in the context. Unlike ``narrate()``, however, you are free to define a callable with any signature, as long as you supply the arguments needed to invoke the callable if need be.\r\n\r\nContext managers may nest, and in fact any combination of function decorator and context manager will work as expected.\r\n\r\n**A larger example**\r\n\r\nLet's look at an example with more complex calling relationships. Suppose we have functions ``A``, ``B``, ``C``, ``D``, ``E``, and ``F``. They have the following calling relationships:\r\n\r\n\r\n* ``A`` calls ``B`` then ``C``\r\n* ``B`` calls ``D``\r\n* ``C`` calls ``E`` or ``F``\r\n* ``D`` calls ``F``\r\n\r\n\r\nWe'll make it so that if we're unlucky enough to call ``E``, we'll get an exception raised. This will happen only for input values of ``A`` greater than 10.\r\n\r\nSo let's define these functions and narrate them-- paste these into an interactive Python session after you've imported ``errator``:\r\n\r\n.. code:: python\r\n\r\n    @narrate(lambda v: \"I'm trying to A with %s as input\" % v)\r\n    def A(val):\r\n        B(val / 2)\r\n        C(val * 2)\r\n\r\n    @narrate(lambda v: \"I'm trying to B with %s as input\" % v)\r\n    def B(val):\r\n        D(val * 10)\r\n\r\n    @narrate(lambda v: \"I'm trying to C with %s as input\" % v)\r\n    def C(val):\r\n        if val > 20:\r\n            E(val)\r\n        else:\r\n            F(val)\r\n\r\n    @narrate(lambda v: \"I'm trying to D with %s as input\" % v)\r\n    def D(val):\r\n        F(val * 3)\r\n\r\n    @narrate(lambda v: \"I'm trying to E with %s as input\" % v)\r\n    def E(val):\r\n        raise ValueError(\"how dare you call me with such a value?\")\r\n\r\n    @narrate(lambda v: \"I'm trying to F with %s as input\" % v)\r\n    def F(val):\r\n        print(\"very well\")\r\n\r\nNow run ``A`` with a value less than 11, and look for narration text:\r\n\r\n.. code:: python\r\n\r\n    >>> A(3)\r\n    very well\r\n    very well\r\n    >>> get_narration()\r\n    []\r\n    >>> \r\n\r\nSince there was no exception, there are no narrations. Now run ``A`` with a value greater than 10, which will cause an exception in E:\r\n\r\n.. code:: python\r\n\r\n    >>> A(11)\r\n    very well\r\n    Traceback (most recent call last):\r\n      File \"<stdin>\", line 1, in <module>\r\n      File \"errator.py\", line 322, in callit\r\n        _v = m(*args, **kwargs)\r\n      File \"<stdin>\", line 4, in A\r\n      File \"errator.py\", line 322, in callit\r\n        _v = m(*args, **kwargs)\r\n      File \"<stdin>\", line 4, in C\r\n      File \"errator.py\", line 322, in callit\r\n        _v = m(*args, **kwargs)\r\n      File \"<stdin>\", line 3, in E\r\n    ValueError: how dare you call me with such a value?\r\n    >>> \r\n\r\nSo far, it's as we'd expect, except perhaps for the inclusion of ``errator`` calls in the stack (``errator`` includes tools that allow you to get stack traces that have been cleaned of ``errator`` calls). But now let's look at the narration:\r\n\r\n.. code::\r\n\r\n    >>> for l in get_narration():\r\n    ...     print(l)\r\n    ... \r\n    I'm trying to A with 11 as input\r\n    I'm trying to C with 22 as input\r\n    I'm trying to E with 22 as input, but exception type: ValueError, value: how dare you call me with such a value? was raised\r\n    >>> \r\n\r\nWe have a narration for our recent exception. Now try the following:\r\n\r\n.. code:: python\r\n\r\n    >>> A(8)\r\n    very well\r\n    very well\r\n    >>> get_narration()\r\n    [\"I'm trying to A with 11 as input\", \"I'm trying to C with 22 as input\", # etc...\r\n\r\nWait, this didn't have an exception; why is there still error narration? This is because *an error narration only gets cleared out if a decorated function does NOT have an exception bubble up*; the assumption is that the exception was caught and the narration was retrieved, so a decorated function that returns normally would remove the previous narration fragments. In our example, there is no function that is decorated with ``narrate()`` that catches the exception and returns normally, so the narration never clears out.\r\n\r\nThere are a few ways to clear unwanted narrations: first is to manually clear the narration, and the other is to make sure you have a decorated function that catches the exception and returns normally, which will clear the narration automatically\r\n\r\nTo manually clear narrations we call ``reset_narration()``:\r\n\r\n.. code:: python\r\n\r\n    >>> reset_narration()\r\n    >>> get_narration()\r\n    >>> []\r\n\r\nFor the second, if we define a decorated function that calls A but which handles the exception and returns normally, the narration fragments will be cleaned up automatically:\r\n\r\n.. code:: python\r\n\r\n    @narrate(\"Handler for A\")\r\n    def first(val):\r\n        try:\r\n            A(val)\r\n        except:\r\n            print(\"Got %d narration lines\" % len(get_narration()))\r\n\r\nThis outermost function still can retrieve the narration, but as it returns normally, the narration is cleared out when it returns:\r\n\r\n.. code:: python\r\n\r\n    >>> first(11)\r\n    very well\r\n    Got 4 narration lines\r\n    >>> get_narration()\r\n    []\r\n    >>> \r\n\r\n``errator`` provides various narration options and finer degrees of control for retriving the narration; these are covered in the detailed docs. See the ``using_errator`` file in the docs directory.\r\n\r\nBuilding from source\r\n--------------------\r\n\r\nIf there isn't a pre-built distribution for your platform, you can build ``errator`` yourself. You'll need:\r\n\r\n- A C compiler\r\n- Python header files for your version of Python\r\n- Cython\r\n\r\nThere are now two setup.py files, one for Python 2 and the other for 3 (setup2.py, setup3.py), which will undoubtedly break something somewhere.\r\n\r\nIn the project root, run the following command:\r\n\r\n.. code::\r\n\r\n    python setup(2|3).py build_ext --inplace\r\n\r\n...using the value 2 or 3, depending on the version of Python you're building for. This will create the shared library that is used by ``errator``. You can then do the normal ``python setup.py install`` dance to put the built distribution where you want it to go, or you can simply use it right from where you built it.\r\n\r\nIf you want to build a wheel, the command is:\r\n\r\n.. code::\r\n\r\n    python setup(2|3).py bdist_wheel --python-tag py(2|3)\r\n\r\n...again, selecting the value 2 or 3 consistently depending on your Python version.\r\n\r\n\r\n", "description_content_type": "", "docs_url": "https://pythonhosted.org/errator/", "download_url": "https://github.com/haxsaw/errator/archive/0.3.3.tar.gz", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "https://github.com/haxsaw/errator", "keywords": "exception,logging,traceback,stacktrace", "license": "MIT", "maintainer": "", "maintainer_email": "", "name": "errator", "package_url": "https://pypi.org/project/errator/", "platform": "", "project_url": "https://pypi.org/project/errator/", "project_urls": {"Download": "https://github.com/haxsaw/errator/archive/0.3.3.tar.gz", "Homepage": "https://github.com/haxsaw/errator"}, "release_url": "https://pypi.org/project/errator/0.3.3/", "requires_dist": null, "requires_python": "", "summary": "Errator allows you to create human-readable exception narrations", "version": "0.3.3", "yanked": false, "html_description": "<div class=\"project-description\">\n            <p>Provide human-readable error narration of exception tracebacks with <tt>errator</tt>.</p>\n<ol>\n<li><a href=\"#what-s-new-in-0-3\" rel=\"nofollow\">What\u2019s new in 0.3</a></li>\n<li><a href=\"#intro\" rel=\"nofollow\">Intro</a></li>\n<li><a href=\"#how-it-works\" rel=\"nofollow\">How it works</a></li>\n<li><a href=\"#requirements\" rel=\"nofollow\">Requirements</a></li>\n<li><a href=\"#installing\" rel=\"nofollow\">Installing</a></li>\n<li><a href=\"#quick-start\" rel=\"nofollow\">Quick Start</a></li>\n<li><a href=\"#building-from-source\" rel=\"nofollow\">Building from source</a></li>\n</ol>\n<div id=\"what-s-new-in-0-3\">\n<h2>What\u2019s new in 0.3</h2>\n<p>This is largely a performance release for <tt>errator</tt>, as it implements the more costly part of the narration process in a <a href=\"http://cython.org/\" rel=\"nofollow\">Cython</a> extension. Additionally, there has been a change in the way verbose narrations are performed, as the original approach entailed a lot of overhead even if verbose narrations weren\u2019t required.</p>\n<ul>\n<li><tt>errator</tt> now consists of a Python file and a  Python extension module (built from a Cython source), which improves runtime performance</li>\n<li>The \u2018verbose\u2019 keyword argument has been removed from the <tt>get_narration()</tt> function, and has been added to the <tt>set_narration_options()</tt> and <tt>set_default_options()</tt> functions. Now getting verbose narrations is a matter of setting the option either as a default or on a per-thread basis, hence this option must be set <cite>before</cite> collecting narrations.</li>\n<li>Previously, detailed exception information (file name, line number) was always collected in case a user wanted to fetch verbose narration information with <tt>get_narration()</tt>. However, this proved to be a big performance hit, and now this information is <cite>only</cite> collected if the \u2018verbose\u2019 option has been set with <tt>set_narration_options()</tt> or <tt>set_default_options()</tt> function <cite>before</cite> the exception occurs.</li>\n</ul>\n</div>\n<div id=\"what-s-new-in-0-2-1\">\n<h2>What\u2019s new in 0.2.1</h2>\n<p>This patch release addresses certain performance issues:</p>\n<ul>\n<li>Patched a bug that caused too many object creations to occur</li>\n<li>Removed some redundant resetting of state in narration fragment objects</li>\n<li>Added caching of filenames for function objects so that lookups aren\u2019t always required</li>\n<li>Sped up the resetting process</li>\n</ul>\n</div>\n<div id=\"what-s-new-in-0-2\">\n<h2>What\u2019s new in 0.2</h2>\n<ul>\n<li>The <tt>get_narration()</tt> now has a new keyword argument, \u201cverbose\u201d (default False), that when True returns expanded narration information that includes the line number, function, and file name of the point in the stack trace that the narration applies to.</li>\n<li>To provide a more tidy display of stack information, <tt>errator</tt> now has analogs of the functions from the standard <tt>traceback</tt> module that filter out <tt>errator</tt>-based calls from the call stack, leaving only application calls in the display of stack traces.</li>\n<li>Narration output formatting has been modified slightly.</li>\n</ul>\n</div>\n<div id=\"intro\">\n<h2>Intro</h2>\n<p><tt>errator</tt> came as an idea on the back of trying to figure out what the semantics of an exception traceback are in non-trivial pieces of code.</p>\n<p>When an exception occurs deep inside a call stack within some generic utility function that is used in numerous contexts, reading the traceback is often not helpful in determining the source of the problem. Data values aren\u2019t obvious, and the initial starting conditions of the error can\u2019t easily been seen.</p>\n<p>Logging is a step in the right direction, but in general outputs too much information; often, there is lots of info regarding error-free processing in the log, making it hard to find the right log output that is associated with the error.</p>\n<p><tt>errator</tt> is something of a marriage between logging and tracebacks: plain text messages that are associated directly with the call trail that led to an exception. <tt>errator</tt> works by providing tools that let you state intent of code in text, but only captures that text when an exception bubbles up the stack. You can then acquire this \u201cerror narration\u201d and display it to your user in the most appropriate fashion.</p>\n</div>\n<div id=\"how-it-works\">\n<h2>How it works</h2>\n<p><tt>errator</tt> uses decorators and context managers to maintain a stack of \u201cnarration fragments\u201d behind the scenes. When code executes without exceptions, these fragments are created and thrown away as narrated code executes and returns. However, when an exception is raised, the narration fragments are retained and their content can be retrieved. Fragments can be automatically discarded (pruned) when an exception doesn\u2019t propagate any further up the stack, or can be discarded under user control, allowing more control over the content of \u201cnarration\u201d provided for the exception.</p>\n<p><tt>errator</tt> is thread-safe, allowing you to capture separate error narrations for independent threads of control through the same code.</p>\n</div>\n<div id=\"requirements\">\n<h2>Requirements</h2>\n<p><tt>errator</tt> doesn\u2019t have any runtime external dependencies, and is compatible with Python 2.7 and 3.x. If you wish to build from source, you\u2019ll need to install Cython to build the extension module, and have a C compiler and the required Python header files.</p>\n</div>\n<div id=\"installing\">\n<h2>Installing</h2>\n<p>As of 0.3, <tt>errator</tt> is comprised of a Python module and an extension wrapper. You can install it with <tt>pip install errator</tt>, or you can clone the Git project and build from source (more on this below).</p>\n</div>\n<div id=\"quick-start\">\n<h2>Quick Start</h2>\n<p>The next section discusses <tt>errator</tt> with functions, but you can also use the decorators described with methods too.</p>\n<p><strong>Basic Use</strong></p>\n<p>Start by importing <tt>errator</tt> into the module that you want to narrate:</p>\n<pre><span class=\"kn\">from</span> <span class=\"nn\">errator</span> <span class=\"kn\">import</span> <span class=\"o\">*</span>\n</pre>\n<p>Now, suppose you have a utility function that performs some specialized string formatting, but it is possible to pass in arguments that cause a exception to be raised. Your function is called all over the place for a variety of different reasons, often very deep down the call stack where it isn\u2019t obvious what the original functional intent was, or where the source of bad arguments may have been.</p>\n<p>To start building the narration to your function\u2019s execution, you can use the <tt>narrate()</tt> decorator to associate a bit of text with your utility function in order to provide easily understandable explanations about what\u2019s going on:</p>\n<pre><span class=\"nd\">@narrate</span><span class=\"p\">(</span><span class=\"s2\">\"I'm trying to format a string\"</span><span class=\"p\">)</span>\n<span class=\"k\">def</span> <span class=\"nf\">special_formatter</span><span class=\"p\">(</span><span class=\"n\">fmt_string</span><span class=\"p\">,</span> <span class=\"o\">**</span><span class=\"n\">kwargs</span><span class=\"p\">):</span>\n    <span class=\"c1\"># magic format code that sometimes raises an exception</span>\n</pre>\n<p>The <tt>narrate()</tt> decorator knows to look for exceptions and doesn\u2019t impede their propagation, but captures that bit of text in an internal stack when an exception occurs. So if you write:</p>\n<pre><span class=\"k\">try</span><span class=\"p\">:</span>\n    <span class=\"n\">s</span> <span class=\"o\">=</span> <span class=\"n\">special_formatter</span><span class=\"p\">(</span><span class=\"n\">fmt</span><span class=\"p\">,</span> <span class=\"o\">**</span><span class=\"n\">args</span><span class=\"p\">)</span>\n<span class=\"n\">exception</span> <span class=\"ne\">Exception</span><span class=\"p\">:</span>\n    <span class=\"n\">the_tale</span> <span class=\"o\">=</span> <span class=\"n\">get_narration</span><span class=\"p\">()</span>\n</pre>\n<p>\u2026and <tt>special_formatter()</tt> raises an exception, the exception will still bubble up the stack, but <tt>get_narration()</tt> will return a list of strings for all the <tt>narrate()</tt>-decorated functions down to the exception. If no exception is raised, there are no strings to fetch (unless you want there to be strings, but we\u2019ll get to that).</p>\n<p><strong>Getting more information</strong></p>\n<p>Maybe you\u2019d like some insight as to the value of the arguments passed when an exception is raised, so you can better tell what\u2019s causing it. Instead of a string, you can supply the <tt>narrate()</tt> decorator with a callable that returns a string and that has the same signature as the function being decorated. This callable will <cite>only be invoked if the decorated function raises an exception</cite>, and gets invoked with the same arguments as the function:</p>\n<pre><span class=\"nd\">@narrate</span><span class=\"p\">(</span><span class=\"k\">lambda</span> <span class=\"n\">fs</span><span class=\"p\">,</span> <span class=\"o\">**</span><span class=\"n\">kw</span><span class=\"p\">:</span> <span class=\"s2\">\"I'm trying to format a string with '</span><span class=\"si\">%s</span><span class=\"s2\">' and args '</span><span class=\"si\">%s</span><span class=\"s2\">'\"</span> <span class=\"o\">%</span> <span class=\"p\">(</span><span class=\"n\">fs</span><span class=\"p\">,</span> <span class=\"nb\">str</span><span class=\"p\">(</span><span class=\"n\">kw</span><span class=\"p\">)))</span>\n<span class=\"k\">def</span> <span class=\"nf\">special_formatter</span><span class=\"p\">(</span><span class=\"n\">fmt_string</span><span class=\"p\">,</span> <span class=\"o\">**</span><span class=\"n\">kwargs</span><span class=\"p\">):</span>\n    <span class=\"c1\"># magic format code that sometimes raises an exception</span>\n</pre>\n<p>The lambda passed to narrate() will only be called when <tt>special_formatter()</tt> raises an exception, otherwise it will go un-executed.</p>\n<p><strong>Finer details with contexts</strong></p>\n<p>Now, perhaps <tt>special_formatter()</tt> is a rather long function, and you\u2019d like to be able to narrate it\u2019s operation in more detail to get better narrations when things go wrong. You can use the <tt>narrate_cm()</tt> context manager to create a narration fragment for a block of code. If everything goes well in the block, then the fragment is discarded, but the fragment will be retained if an exception occurs:</p>\n<pre><span class=\"k\">def</span> <span class=\"nf\">special_formatter</span><span class=\"p\">(</span><span class=\"n\">fmt_string</span><span class=\"p\">,</span> <span class=\"o\">**</span><span class=\"n\">kwargs</span><span class=\"p\">):</span>\n    <span class=\"k\">for</span> <span class=\"n\">format_token</span> <span class=\"ow\">in</span> <span class=\"n\">parse_format</span><span class=\"p\">(</span><span class=\"n\">fmt_string</span><span class=\"p\">):</span>\n        <span class=\"k\">if</span> <span class=\"n\">format_token</span><span class=\"o\">.</span><span class=\"n\">type</span> <span class=\"o\">==</span> <span class=\"nb\">float</span><span class=\"p\">:</span>\n            <span class=\"k\">with</span> <span class=\"n\">narrate_cm</span><span class=\"p\">(</span><span class=\"s2\">\"I started processing a float format\"</span><span class=\"p\">):</span>\n                <span class=\"c1\"># do magic stuff for floats...</span>\n        <span class=\"k\">elif</span> <span class=\"n\">format_token</span><span class=\"o\">.</span><span class=\"n\">type</span> <span class=\"o\">==</span> <span class=\"nb\">int</span><span class=\"p\">:</span>\n            <span class=\"k\">with</span> <span class=\"n\">narrate_cm</span><span class=\"p\">(</span><span class=\"s2\">\"I started processing an int format\"</span><span class=\"p\">):</span>\n                <span class=\"c1\"># do magic stuff for ints...</span>\n</pre>\n<p>Narration fragments added with <tt>narrate_cm()</tt> are treated just like those created by the function decorator\u2013 they are added to the stack, and silently removed if the context manager\u2019s code block exits normally. But exceptions raised in the context block are retained as the exception propagates back through the stack.</p>\n<p>Like <tt>narrate()</tt>, <tt>narrate\\_cm()</tt> allows you to supply a callable instead of\na string:</p>\n<pre><span class=\"k\">with</span> <span class=\"n\">narrate_cm</span><span class=\"p\">(</span><span class=\"k\">lambda</span> <span class=\"n\">x</span><span class=\"p\">:</span> <span class=\"s2\">\"I started processing an int with format </span><span class=\"si\">%s</span><span class=\"s2\">\"</span> <span class=\"o\">%</span> <span class=\"n\">x</span><span class=\"p\">,</span> <span class=\"n\">format_token</span><span class=\"o\">.</span><span class=\"n\">format</span><span class=\"p\">):</span>\n    <span class=\"c1\"># format code</span>\n</pre>\n<p>\u2026and again, this callable will only be invoked if an exception is raised in the context. Unlike <tt>narrate()</tt>, however, you are free to define a callable with any signature, as long as you supply the arguments needed to invoke the callable if need be.</p>\n<p>Context managers may nest, and in fact any combination of function decorator and context manager will work as expected.</p>\n<p><strong>A larger example</strong></p>\n<p>Let\u2019s look at an example with more complex calling relationships. Suppose we have functions <tt>A</tt>, <tt>B</tt>, <tt>C</tt>, <tt>D</tt>, <tt>E</tt>, and <tt>F</tt>. They have the following calling relationships:</p>\n<ul>\n<li><tt>A</tt> calls <tt>B</tt> then <tt>C</tt></li>\n<li><tt>B</tt> calls <tt>D</tt></li>\n<li><tt>C</tt> calls <tt>E</tt> or <tt>F</tt></li>\n<li><tt>D</tt> calls <tt>F</tt></li>\n</ul>\n<p>We\u2019ll make it so that if we\u2019re unlucky enough to call <tt>E</tt>, we\u2019ll get an exception raised. This will happen only for input values of <tt>A</tt> greater than 10.</p>\n<p>So let\u2019s define these functions and narrate them\u2013 paste these into an interactive Python session after you\u2019ve imported <tt>errator</tt>:</p>\n<pre><span class=\"nd\">@narrate</span><span class=\"p\">(</span><span class=\"k\">lambda</span> <span class=\"n\">v</span><span class=\"p\">:</span> <span class=\"s2\">\"I'm trying to A with </span><span class=\"si\">%s</span><span class=\"s2\"> as input\"</span> <span class=\"o\">%</span> <span class=\"n\">v</span><span class=\"p\">)</span>\n<span class=\"k\">def</span> <span class=\"nf\">A</span><span class=\"p\">(</span><span class=\"n\">val</span><span class=\"p\">):</span>\n    <span class=\"n\">B</span><span class=\"p\">(</span><span class=\"n\">val</span> <span class=\"o\">/</span> <span class=\"mi\">2</span><span class=\"p\">)</span>\n    <span class=\"n\">C</span><span class=\"p\">(</span><span class=\"n\">val</span> <span class=\"o\">*</span> <span class=\"mi\">2</span><span class=\"p\">)</span>\n\n<span class=\"nd\">@narrate</span><span class=\"p\">(</span><span class=\"k\">lambda</span> <span class=\"n\">v</span><span class=\"p\">:</span> <span class=\"s2\">\"I'm trying to B with </span><span class=\"si\">%s</span><span class=\"s2\"> as input\"</span> <span class=\"o\">%</span> <span class=\"n\">v</span><span class=\"p\">)</span>\n<span class=\"k\">def</span> <span class=\"nf\">B</span><span class=\"p\">(</span><span class=\"n\">val</span><span class=\"p\">):</span>\n    <span class=\"n\">D</span><span class=\"p\">(</span><span class=\"n\">val</span> <span class=\"o\">*</span> <span class=\"mi\">10</span><span class=\"p\">)</span>\n\n<span class=\"nd\">@narrate</span><span class=\"p\">(</span><span class=\"k\">lambda</span> <span class=\"n\">v</span><span class=\"p\">:</span> <span class=\"s2\">\"I'm trying to C with </span><span class=\"si\">%s</span><span class=\"s2\"> as input\"</span> <span class=\"o\">%</span> <span class=\"n\">v</span><span class=\"p\">)</span>\n<span class=\"k\">def</span> <span class=\"nf\">C</span><span class=\"p\">(</span><span class=\"n\">val</span><span class=\"p\">):</span>\n    <span class=\"k\">if</span> <span class=\"n\">val</span> <span class=\"o\">&gt;</span> <span class=\"mi\">20</span><span class=\"p\">:</span>\n        <span class=\"n\">E</span><span class=\"p\">(</span><span class=\"n\">val</span><span class=\"p\">)</span>\n    <span class=\"k\">else</span><span class=\"p\">:</span>\n        <span class=\"n\">F</span><span class=\"p\">(</span><span class=\"n\">val</span><span class=\"p\">)</span>\n\n<span class=\"nd\">@narrate</span><span class=\"p\">(</span><span class=\"k\">lambda</span> <span class=\"n\">v</span><span class=\"p\">:</span> <span class=\"s2\">\"I'm trying to D with </span><span class=\"si\">%s</span><span class=\"s2\"> as input\"</span> <span class=\"o\">%</span> <span class=\"n\">v</span><span class=\"p\">)</span>\n<span class=\"k\">def</span> <span class=\"nf\">D</span><span class=\"p\">(</span><span class=\"n\">val</span><span class=\"p\">):</span>\n    <span class=\"n\">F</span><span class=\"p\">(</span><span class=\"n\">val</span> <span class=\"o\">*</span> <span class=\"mi\">3</span><span class=\"p\">)</span>\n\n<span class=\"nd\">@narrate</span><span class=\"p\">(</span><span class=\"k\">lambda</span> <span class=\"n\">v</span><span class=\"p\">:</span> <span class=\"s2\">\"I'm trying to E with </span><span class=\"si\">%s</span><span class=\"s2\"> as input\"</span> <span class=\"o\">%</span> <span class=\"n\">v</span><span class=\"p\">)</span>\n<span class=\"k\">def</span> <span class=\"nf\">E</span><span class=\"p\">(</span><span class=\"n\">val</span><span class=\"p\">):</span>\n    <span class=\"k\">raise</span> <span class=\"ne\">ValueError</span><span class=\"p\">(</span><span class=\"s2\">\"how dare you call me with such a value?\"</span><span class=\"p\">)</span>\n\n<span class=\"nd\">@narrate</span><span class=\"p\">(</span><span class=\"k\">lambda</span> <span class=\"n\">v</span><span class=\"p\">:</span> <span class=\"s2\">\"I'm trying to F with </span><span class=\"si\">%s</span><span class=\"s2\"> as input\"</span> <span class=\"o\">%</span> <span class=\"n\">v</span><span class=\"p\">)</span>\n<span class=\"k\">def</span> <span class=\"nf\">F</span><span class=\"p\">(</span><span class=\"n\">val</span><span class=\"p\">):</span>\n    <span class=\"nb\">print</span><span class=\"p\">(</span><span class=\"s2\">\"very well\"</span><span class=\"p\">)</span>\n</pre>\n<p>Now run <tt>A</tt> with a value less than 11, and look for narration text:</p>\n<pre><span class=\"o\">&gt;&gt;&gt;</span> <span class=\"n\">A</span><span class=\"p\">(</span><span class=\"mi\">3</span><span class=\"p\">)</span>\n<span class=\"n\">very</span> <span class=\"n\">well</span>\n<span class=\"n\">very</span> <span class=\"n\">well</span>\n<span class=\"o\">&gt;&gt;&gt;</span> <span class=\"n\">get_narration</span><span class=\"p\">()</span>\n<span class=\"p\">[]</span>\n<span class=\"o\">&gt;&gt;&gt;</span>\n</pre>\n<p>Since there was no exception, there are no narrations. Now run <tt>A</tt> with a value greater than 10, which will cause an exception in E:</p>\n<pre><span class=\"o\">&gt;&gt;&gt;</span> <span class=\"n\">A</span><span class=\"p\">(</span><span class=\"mi\">11</span><span class=\"p\">)</span>\n<span class=\"n\">very</span> <span class=\"n\">well</span>\n<span class=\"n\">Traceback</span> <span class=\"p\">(</span><span class=\"n\">most</span> <span class=\"n\">recent</span> <span class=\"n\">call</span> <span class=\"n\">last</span><span class=\"p\">):</span>\n  <span class=\"n\">File</span> <span class=\"s2\">\"&lt;stdin&gt;\"</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">1</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"o\">&lt;</span><span class=\"n\">module</span><span class=\"o\">&gt;</span>\n  <span class=\"n\">File</span> <span class=\"s2\">\"errator.py\"</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">322</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">callit</span>\n    <span class=\"n\">_v</span> <span class=\"o\">=</span> <span class=\"n\">m</span><span class=\"p\">(</span><span class=\"o\">*</span><span class=\"n\">args</span><span class=\"p\">,</span> <span class=\"o\">**</span><span class=\"n\">kwargs</span><span class=\"p\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">\"&lt;stdin&gt;\"</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">4</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">A</span>\n  <span class=\"n\">File</span> <span class=\"s2\">\"errator.py\"</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">322</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">callit</span>\n    <span class=\"n\">_v</span> <span class=\"o\">=</span> <span class=\"n\">m</span><span class=\"p\">(</span><span class=\"o\">*</span><span class=\"n\">args</span><span class=\"p\">,</span> <span class=\"o\">**</span><span class=\"n\">kwargs</span><span class=\"p\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">\"&lt;stdin&gt;\"</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">4</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">C</span>\n  <span class=\"n\">File</span> <span class=\"s2\">\"errator.py\"</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">322</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">callit</span>\n    <span class=\"n\">_v</span> <span class=\"o\">=</span> <span class=\"n\">m</span><span class=\"p\">(</span><span class=\"o\">*</span><span class=\"n\">args</span><span class=\"p\">,</span> <span class=\"o\">**</span><span class=\"n\">kwargs</span><span class=\"p\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">\"&lt;stdin&gt;\"</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">3</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">E</span>\n<span class=\"ne\">ValueError</span><span class=\"p\">:</span> <span class=\"n\">how</span> <span class=\"n\">dare</span> <span class=\"n\">you</span> <span class=\"n\">call</span> <span class=\"n\">me</span> <span class=\"k\">with</span> <span class=\"n\">such</span> <span class=\"n\">a</span> <span class=\"n\">value</span><span class=\"err\">?</span>\n<span class=\"o\">&gt;&gt;&gt;</span>\n</pre>\n<p>So far, it\u2019s as we\u2019d expect, except perhaps for the inclusion of <tt>errator</tt> calls in the stack (<tt>errator</tt> includes tools that allow you to get stack traces that have been cleaned of <tt>errator</tt> calls). But now let\u2019s look at the narration:</p>\n<pre>&gt;&gt;&gt; for l in get_narration():\n...     print(l)\n...\nI'm trying to A with 11 as input\nI'm trying to C with 22 as input\nI'm trying to E with 22 as input, but exception type: ValueError, value: how dare you call me with such a value? was raised\n&gt;&gt;&gt;\n</pre>\n<p>We have a narration for our recent exception. Now try the following:</p>\n<pre><span class=\"o\">&gt;&gt;&gt;</span> <span class=\"n\">A</span><span class=\"p\">(</span><span class=\"mi\">8</span><span class=\"p\">)</span>\n<span class=\"n\">very</span> <span class=\"n\">well</span>\n<span class=\"n\">very</span> <span class=\"n\">well</span>\n<span class=\"o\">&gt;&gt;&gt;</span> <span class=\"n\">get_narration</span><span class=\"p\">()</span>\n<span class=\"p\">[</span><span class=\"s2\">\"I'm trying to A with 11 as input\"</span><span class=\"p\">,</span> <span class=\"s2\">\"I'm trying to C with 22 as input\"</span><span class=\"p\">,</span> <span class=\"c1\"># etc...</span>\n</pre>\n<p>Wait, this didn\u2019t have an exception; why is there still error narration? This is because <em>an error narration only gets cleared out if a decorated function does NOT have an exception bubble up</em>; the assumption is that the exception was caught and the narration was retrieved, so a decorated function that returns normally would remove the previous narration fragments. In our example, there is no function that is decorated with <tt>narrate()</tt> that catches the exception and returns normally, so the narration never clears out.</p>\n<p>There are a few ways to clear unwanted narrations: first is to manually clear the narration, and the other is to make sure you have a decorated function that catches the exception and returns normally, which will clear the narration automatically</p>\n<p>To manually clear narrations we call <tt>reset_narration()</tt>:</p>\n<pre><span class=\"o\">&gt;&gt;&gt;</span> <span class=\"n\">reset_narration</span><span class=\"p\">()</span>\n<span class=\"o\">&gt;&gt;&gt;</span> <span class=\"n\">get_narration</span><span class=\"p\">()</span>\n<span class=\"o\">&gt;&gt;&gt;</span> <span class=\"p\">[]</span>\n</pre>\n<p>For the second, if we define a decorated function that calls A but which handles the exception and returns normally, the narration fragments will be cleaned up automatically:</p>\n<pre><span class=\"nd\">@narrate</span><span class=\"p\">(</span><span class=\"s2\">\"Handler for A\"</span><span class=\"p\">)</span>\n<span class=\"k\">def</span> <span class=\"nf\">first</span><span class=\"p\">(</span><span class=\"n\">val</span><span class=\"p\">):</span>\n    <span class=\"k\">try</span><span class=\"p\">:</span>\n        <span class=\"n\">A</span><span class=\"p\">(</span><span class=\"n\">val</span><span class=\"p\">)</span>\n    <span class=\"k\">except</span><span class=\"p\">:</span>\n        <span class=\"nb\">print</span><span class=\"p\">(</span><span class=\"s2\">\"Got </span><span class=\"si\">%d</span><span class=\"s2\"> narration lines\"</span> <span class=\"o\">%</span> <span class=\"nb\">len</span><span class=\"p\">(</span><span class=\"n\">get_narration</span><span class=\"p\">()))</span>\n</pre>\n<p>This outermost function still can retrieve the narration, but as it returns normally, the narration is cleared out when it returns:</p>\n<pre><span class=\"o\">&gt;&gt;&gt;</span> <span class=\"n\">first</span><span class=\"p\">(</span><span class=\"mi\">11</span><span class=\"p\">)</span>\n<span class=\"n\">very</span> <span class=\"n\">well</span>\n<span class=\"n\">Got</span> <span class=\"mi\">4</span> <span class=\"n\">narration</span> <span class=\"n\">lines</span>\n<span class=\"o\">&gt;&gt;&gt;</span> <span class=\"n\">get_narration</span><span class=\"p\">()</span>\n<span class=\"p\">[]</span>\n<span class=\"o\">&gt;&gt;&gt;</span>\n</pre>\n<p><tt>errator</tt> provides various narration options and finer degrees of control for retriving the narration; these are covered in the detailed docs. See the <tt>using_errator</tt> file in the docs directory.</p>\n</div>\n<div id=\"building-from-source\">\n<h2>Building from source</h2>\n<p>If there isn\u2019t a pre-built distribution for your platform, you can build <tt>errator</tt> yourself. You\u2019ll need:</p>\n<ul>\n<li>A C compiler</li>\n<li>Python header files for your version of Python</li>\n<li>Cython</li>\n</ul>\n<p>There are now two setup.py files, one for Python 2 and the other for 3 (setup2.py, setup3.py), which will undoubtedly break something somewhere.</p>\n<p>In the project root, run the following command:</p>\n<pre>python setup(2|3).py build_ext --inplace\n</pre>\n<p>\u2026using the value 2 or 3, depending on the version of Python you\u2019re building for. This will create the shared library that is used by <tt>errator</tt>. You can then do the normal <tt>python setup.py install</tt> dance to put the built distribution where you want it to go, or you can simply use it right from where you built it.</p>\n<p>If you want to build a wheel, the command is:</p>\n<pre>python setup(2|3).py bdist_wheel --python-tag py(2|3)\n</pre>\n<p>\u2026again, selecting the value 2 or 3 consistently depending on your Python version.</p>\n</div>\n\n          </div>"}, "last_serial": 3777367, "releases": {"0.1": [], "0.1.2": [{"comment_text": "", "digests": {"md5": "03374a3611a3229e5daf112c592e0bd6", "sha256": "0f98ba774a0c7adaec486e6b6c79152b68460f928b9688eae2f5a38913acd3a9"}, "downloads": -1, "filename": "errator-0.1.2.tar.gz", "has_sig": false, "md5_digest": "03374a3611a3229e5daf112c592e0bd6", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 5397, "upload_time": "2016-06-29T12:08:02", "upload_time_iso_8601": "2016-06-29T12:08:02.411317Z", "url": "https://files.pythonhosted.org/packages/38/e2/b315c752407d601d42077aab090129b3bc4aefaf41e9329de93151b45ed6/errator-0.1.2.tar.gz", "yanked": false}], "0.1.3": [{"comment_text": "", "digests": {"md5": "c1970d9d5c9550ea31daede446081a1e", "sha256": "23d8d48f476d528bdb9080ce78c9080799bcf891bce255de9c8dcb1c6d88e29b"}, "downloads": -1, "filename": "errator-0.1.3.tar.gz", "has_sig": false, "md5_digest": "c1970d9d5c9550ea31daede446081a1e", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 5636, "upload_time": "2016-06-29T15:17:11", "upload_time_iso_8601": "2016-06-29T15:17:11.198978Z", "url": "https://files.pythonhosted.org/packages/40/57/9c710e63b468b0a14ca7146fbdf4ed5b9de751cde3851246172854a68842/errator-0.1.3.tar.gz", "yanked": false}], "0.2": [{"comment_text": "", "digests": {"md5": "55158f9b567b121b98bf283c410d98a8", "sha256": "b7c0d56895fa5cb34358e5b435e06ce92acf7c288f8caca8bdd3dcdd7295e3ff"}, "downloads": -1, "filename": "errator-0.2.tar.gz", "has_sig": false, "md5_digest": "55158f9b567b121b98bf283c410d98a8", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 7795, "upload_time": "2017-02-17T15:06:34", "upload_time_iso_8601": "2017-02-17T15:06:34.093890Z", "url": "https://files.pythonhosted.org/packages/e7/20/a24769cdb797347b95364890527a97e27e28150e15d06e305aa76ab0cb31/errator-0.2.tar.gz", "yanked": false}], "0.3.3": [{"comment_text": "", "digests": {"md5": "0d8d513cd67f6fda1fe07fa968bda450", "sha256": "66f8360413695f9f5b414546a6abdd1d151befc996ac317c3ea499337abac62d"}, "downloads": -1, "filename": "errator-0.3.3-cp27-cp27m-win32.whl", "has_sig": false, "md5_digest": "0d8d513cd67f6fda1fe07fa968bda450", "packagetype": "bdist_wheel", "python_version": "cp27", "requires_python": null, "size": 74265, "upload_time": "2018-04-18T14:19:24", "upload_time_iso_8601": "2018-04-18T14:19:24.401406Z", "url": "https://files.pythonhosted.org/packages/84/66/c9019bf78e2087b80f7bf5704b308b428686e601e5356c9b260867e020f9/errator-0.3.3-cp27-cp27m-win32.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "3cc4293b7ee63f26854b27e412796364", "sha256": "0f2f36b1239d084e4f960a750193dacae3c18e54a7b21ae8d88196c766300364"}, "downloads": -1, "filename": "errator-0.3.3-cp35-cp35m-win_amd64.whl", "has_sig": false, "md5_digest": "3cc4293b7ee63f26854b27e412796364", "packagetype": "bdist_wheel", "python_version": "cp35", "requires_python": null, "size": 83775, "upload_time": "2018-04-18T14:19:25", "upload_time_iso_8601": "2018-04-18T14:19:25.848509Z", "url": "https://files.pythonhosted.org/packages/5b/91/f3741aad4a3a04961b7310d5474604a0dd535102f75729fd3485d7fcf4a4/errator-0.3.3-cp35-cp35m-win_amd64.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "088549a104fbfe168cceb8d15fedc794", "sha256": "64d5f8e306a1f365337000788173cd897a60436a7de19ef884f80e439d77e7da"}, "downloads": -1, "filename": "errator-0.3.3-cp36-cp36m-win_amd64.whl", "has_sig": false, "md5_digest": "088549a104fbfe168cceb8d15fedc794", "packagetype": "bdist_wheel", "python_version": "cp36", "requires_python": null, "size": 91313, "upload_time": "2018-04-18T14:19:27", "upload_time_iso_8601": "2018-04-18T14:19:27.291994Z", "url": "https://files.pythonhosted.org/packages/3b/cf/28a7bc2f0f596f087ee310451d12e34b8406af3ec7c78506a448e724ba03/errator-0.3.3-cp36-cp36m-win_amd64.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "a448f755060baaf6ecd9db09fad15ea9", "sha256": "b84b0c8798d0c2542d1232de297aa755ca8c918b23f149d42335cc59e3005a40"}, "downloads": -1, "filename": "errator-0.3.3.tar.gz", "has_sig": false, "md5_digest": "a448f755060baaf6ecd9db09fad15ea9", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 115827, "upload_time": "2018-04-18T14:19:29", "upload_time_iso_8601": "2018-04-18T14:19:29.245744Z", "url": "https://files.pythonhosted.org/packages/9e/d8/ed82f7abf7e580c61670d8ea0448293a03afd87f14d3a5093aa4bb4e78a1/errator-0.3.3.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "0d8d513cd67f6fda1fe07fa968bda450", "sha256": "66f8360413695f9f5b414546a6abdd1d151befc996ac317c3ea499337abac62d"}, "downloads": -1, "filename": "errator-0.3.3-cp27-cp27m-win32.whl", "has_sig": false, "md5_digest": "0d8d513cd67f6fda1fe07fa968bda450", "packagetype": "bdist_wheel", "python_version": "cp27", "requires_python": null, "size": 74265, "upload_time": "2018-04-18T14:19:24", "upload_time_iso_8601": "2018-04-18T14:19:24.401406Z", "url": "https://files.pythonhosted.org/packages/84/66/c9019bf78e2087b80f7bf5704b308b428686e601e5356c9b260867e020f9/errator-0.3.3-cp27-cp27m-win32.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "3cc4293b7ee63f26854b27e412796364", "sha256": "0f2f36b1239d084e4f960a750193dacae3c18e54a7b21ae8d88196c766300364"}, "downloads": -1, "filename": "errator-0.3.3-cp35-cp35m-win_amd64.whl", "has_sig": false, "md5_digest": "3cc4293b7ee63f26854b27e412796364", "packagetype": "bdist_wheel", "python_version": "cp35", "requires_python": null, "size": 83775, "upload_time": "2018-04-18T14:19:25", "upload_time_iso_8601": "2018-04-18T14:19:25.848509Z", "url": "https://files.pythonhosted.org/packages/5b/91/f3741aad4a3a04961b7310d5474604a0dd535102f75729fd3485d7fcf4a4/errator-0.3.3-cp35-cp35m-win_amd64.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "088549a104fbfe168cceb8d15fedc794", "sha256": "64d5f8e306a1f365337000788173cd897a60436a7de19ef884f80e439d77e7da"}, "downloads": -1, "filename": "errator-0.3.3-cp36-cp36m-win_amd64.whl", "has_sig": false, "md5_digest": "088549a104fbfe168cceb8d15fedc794", "packagetype": "bdist_wheel", "python_version": "cp36", "requires_python": null, "size": 91313, "upload_time": "2018-04-18T14:19:27", "upload_time_iso_8601": "2018-04-18T14:19:27.291994Z", "url": "https://files.pythonhosted.org/packages/3b/cf/28a7bc2f0f596f087ee310451d12e34b8406af3ec7c78506a448e724ba03/errator-0.3.3-cp36-cp36m-win_amd64.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "a448f755060baaf6ecd9db09fad15ea9", "sha256": "b84b0c8798d0c2542d1232de297aa755ca8c918b23f149d42335cc59e3005a40"}, "downloads": -1, "filename": "errator-0.3.3.tar.gz", "has_sig": false, "md5_digest": "a448f755060baaf6ecd9db09fad15ea9", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 115827, "upload_time": "2018-04-18T14:19:29", "upload_time_iso_8601": "2018-04-18T14:19:29.245744Z", "url": "https://files.pythonhosted.org/packages/9e/d8/ed82f7abf7e580c61670d8ea0448293a03afd87f14d3a5093aa4bb4e78a1/errator-0.3.3.tar.gz", "yanked": false}], "timestamp": "Fri May  8 00:45:45 2020"}