{"info": {"author": "Zest Software", "author_email": "m.van.rees@zestsoftware.nl", "bugtrack_url": null, "classifiers": ["Framework :: Plone", "Programming Language :: Python", "Topic :: Software Development :: Libraries :: Python Modules"], "description": "Products.Plone3Cleaners: cleanup after migration from Plone 2.5 to 3\n====================================================================\n\nThis package is a collection of browser views that you might need when\nmigrating from Plone 2.5 to Plone 3.  And actually, some of these can\nbe handy also when not migration, like removing portal_factory items\nfrom the portal_catalog.\n\nAdd this package to the eggs of your buildout; no install inside Plone\nis needed.\n\n\nFive local sites\n----------------\n\nLocal sites from Products.Five have changed a lot since the Plone 2.5\ndays.  They need migration.  Products.Five offers the manage_site.html\npage; just add this to the url of your local site and click the\n'Migrate to Five.component' button.  You should try that first, but in\nmy experience that usually does not work.\n\nNote that a default Plone 2.5 Site does not use localsites, so if you\nhave them, then they are from a third party product.  If you see an\nerror like this in the logs when looking at your Plone 3 Site you have a\nproblem::\n\n  2009-06-23 12:30:17 ERROR ZPublisher BeforeTraverse: Error while invoking hook: \"__local_site_hook__\"\n  Traceback (most recent call last):\n    File \"/home/maurits/zopes/Zope-2.10.7-final-py2.4/lib/python/ZPublisher/BeforeTraverse.py\", line 145, in __call__\n      meth(*(container, request, None)[:args])\n  AttributeError: __call__\n\nWe have two browser views that help in fixing this:\n\n- @@find_local_sites: add this to the url of your Plone Site or of\n  your Zope root.  Click the submit button to find all objects with a\n  problematic local site hook.  Your zope instance log will have some\n  details and the page will display links to the objects that need\n  fixing.  The links will point to our second browser view:\n\n- @@update_local_site: add this to the url of an object with an old\n  local site hook that needs fixing.  Likely, calling this will give\n  that same AttributeError once or twice, but you can ignore that as\n  you are about to fix it : click the 'Migrate to Five.component'\n  button.\n\nThe object that had the old local site hook may need some fixes in the\npython code as well.  Ask the developer of the product that this\nobject is from.  Note that a local site hook is not always the right\nsolution; and this migration is not always enough.  In a client\nproject I got rid of one hook and used a simple attribute instead; a\nsecond hook worked fine after the above migration; a third hook needed\na different migration.\n\n\nportal_factory in portal_catalog\n--------------------------------\n\nYou have seen this: you write a catalog query, on one of the brains\nyou do a ``brain.getObject()`` and this fails because the object was\nwrongly added to the catalog while being created and it was not\ncleaned up.  Clean it up with @@factory_cleanup.  You can choose to\nremove those portal_factory brains or remove any brain where\ngetObject() fails.  For various reasons this may find less or more\nitems; certainly it takes a lot longer.\n\n\nHistory of Products.Plone3Cleaners\n==================================\n\n1.1 (2009-08-19)\n----------------\n\n- Added @@factory_cleanup to remove items with '/portal_factory/' in\n  their path from the portal_catalog.  [maurits]\n\n\n1.0 (2009-06-23)\n----------------\n\n- Initial release.  [maurits]", "description_content_type": null, "docs_url": null, "download_url": "UNKNOWN", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "UNKNOWN", "keywords": "", "license": "GPL", "maintainer": null, "maintainer_email": null, "name": "Products.Plone3Cleaners", "package_url": "https://pypi.org/project/Products.Plone3Cleaners/", "platform": "UNKNOWN", "project_url": "https://pypi.org/project/Products.Plone3Cleaners/", "project_urls": {"Download": "UNKNOWN", "Homepage": "UNKNOWN"}, "release_url": "https://pypi.org/project/Products.Plone3Cleaners/1.1/", "requires_dist": null, "requires_python": null, "summary": "Cleanup after migration from Plone 2.5 to 3", "version": "1.1", "yanked": false, "html_description": "<div class=\"project-description\">\n            <div id=\"products-plone3cleaners-cleanup-after-migration-from-plone-2-5-to-3\">\n<h2>Products.Plone3Cleaners: cleanup after migration from Plone 2.5 to 3</h2>\n<p>This package is a collection of browser views that you might need when\nmigrating from Plone 2.5 to Plone 3.  And actually, some of these can\nbe handy also when not migration, like removing portal_factory items\nfrom the portal_catalog.</p>\n<p>Add this package to the eggs of your buildout; no install inside Plone\nis needed.</p>\n<div id=\"five-local-sites\">\n<h3>Five local sites</h3>\n<p>Local sites from Products.Five have changed a lot since the Plone 2.5\ndays.  They need migration.  Products.Five offers the manage_site.html\npage; just add this to the url of your local site and click the\n\u2018Migrate to Five.component\u2019 button.  You should try that first, but in\nmy experience that usually does not work.</p>\n<p>Note that a default Plone 2.5 Site does not use localsites, so if you\nhave them, then they are from a third party product.  If you see an\nerror like this in the logs when looking at your Plone 3 Site you have a\nproblem:</p>\n<pre>2009-06-23 12:30:17 ERROR ZPublisher BeforeTraverse: Error while invoking hook: \"__local_site_hook__\"\nTraceback (most recent call last):\n  File \"/home/maurits/zopes/Zope-2.10.7-final-py2.4/lib/python/ZPublisher/BeforeTraverse.py\", line 145, in __call__\n    meth(*(container, request, None)[:args])\nAttributeError: __call__\n</pre>\n<p>We have two browser views that help in fixing this:</p>\n<ul>\n<li>@@find_local_sites: add this to the url of your Plone Site or of\nyour Zope root.  Click the submit button to find all objects with a\nproblematic local site hook.  Your zope instance log will have some\ndetails and the page will display links to the objects that need\nfixing.  The links will point to our second browser view:</li>\n<li>@@update_local_site: add this to the url of an object with an old\nlocal site hook that needs fixing.  Likely, calling this will give\nthat same AttributeError once or twice, but you can ignore that as\nyou are about to fix it : click the \u2018Migrate to Five.component\u2019\nbutton.</li>\n</ul>\n<p>The object that had the old local site hook may need some fixes in the\npython code as well.  Ask the developer of the product that this\nobject is from.  Note that a local site hook is not always the right\nsolution; and this migration is not always enough.  In a client\nproject I got rid of one hook and used a simple attribute instead; a\nsecond hook worked fine after the above migration; a third hook needed\na different migration.</p>\n</div>\n<div id=\"portal-factory-in-portal-catalog\">\n<h3>portal_factory in portal_catalog</h3>\n<p>You have seen this: you write a catalog query, on one of the brains\nyou do a <tt>brain.getObject()</tt> and this fails because the object was\nwrongly added to the catalog while being created and it was not\ncleaned up.  Clean it up with @@factory_cleanup.  You can choose to\nremove those portal_factory brains or remove any brain where\ngetObject() fails.  For various reasons this may find less or more\nitems; certainly it takes a lot longer.</p>\n</div>\n</div>\n<div id=\"history-of-products-plone3cleaners\">\n<h2>History of Products.Plone3Cleaners</h2>\n<div id=\"id1\">\n<h3>1.1 (2009-08-19)</h3>\n<ul>\n<li>Added @@factory_cleanup to remove items with \u2018/portal_factory/\u2019 in\ntheir path from the portal_catalog.  [maurits]</li>\n</ul>\n</div>\n<div id=\"id2\">\n<h3>1.0 (2009-06-23)</h3>\n<ul>\n<li>Initial release.  [maurits]</li>\n</ul>\n</div>\n</div>\n\n          </div>"}, "last_serial": 748331, "releases": {"1.0": [{"comment_text": "", "digests": {"md5": "8fadae8ef8dab10060e226b64e9d227f", "sha256": "44cfcab7c790031ffed49a63abeedf9698568228e688f628c62fc6ea922d7868"}, "downloads": -1, "filename": "Products.Plone3Cleaners-1.0.tar.gz", "has_sig": false, "md5_digest": "8fadae8ef8dab10060e226b64e9d227f", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 11226, "upload_time": "2009-06-23T14:04:18", "upload_time_iso_8601": "2009-06-23T14:04:18.939657Z", "url": "https://files.pythonhosted.org/packages/de/71/1fffbc3d52cfa1fe5cfef4e8e75789767f8adbea994180f0a77bf2e49515/Products.Plone3Cleaners-1.0.tar.gz", "yanked": false}], "1.1": [{"comment_text": "", "digests": {"md5": "bbf5549eea5189f8f403aafe8ecad203", "sha256": "0170eaf420669f75d4b1999c016c9ddc6780bfc53774f82032ebe3f7c4719dda"}, "downloads": -1, "filename": "Products.Plone3Cleaners-1.1.tar.gz", "has_sig": false, "md5_digest": "bbf5549eea5189f8f403aafe8ecad203", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 12503, "upload_time": "2009-08-19T13:19:58", "upload_time_iso_8601": "2009-08-19T13:19:58.091970Z", "url": "https://files.pythonhosted.org/packages/64/cc/75b8cef49798c2fb795f7077b8f32da246b316f998942fd21435fe22a038/Products.Plone3Cleaners-1.1.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "bbf5549eea5189f8f403aafe8ecad203", "sha256": "0170eaf420669f75d4b1999c016c9ddc6780bfc53774f82032ebe3f7c4719dda"}, "downloads": -1, "filename": "Products.Plone3Cleaners-1.1.tar.gz", "has_sig": false, "md5_digest": "bbf5549eea5189f8f403aafe8ecad203", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 12503, "upload_time": "2009-08-19T13:19:58", "upload_time_iso_8601": "2009-08-19T13:19:58.091970Z", "url": "https://files.pythonhosted.org/packages/64/cc/75b8cef49798c2fb795f7077b8f32da246b316f998942fd21435fe22a038/Products.Plone3Cleaners-1.1.tar.gz", "yanked": false}], "timestamp": "Fri May  8 03:18:04 2020"}