{"info": {"author": "Maurits van Rees", "author_email": "m.van.rees@zestsoftware.nl", "bugtrack_url": null, "classifiers": ["Development Status :: 4 - Beta", "Environment :: Web Environment", "Framework :: Plone", "Framework :: Plone :: 5.2", "License :: OSI Approved :: Zope Public License", "Operating System :: OS Independent", "Programming Language :: Python", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7"], "description": "zest.zodbupdate\n===============\n\nzodbupdate rename dictionary and dexterity patch for Plone 5.2 projects.\n\nSee `post on community.plone.org <https://community.plone.org/t/zodbverify-porting-plone-with-zopedb-to-python3/8806/13>`_.\nAnd the `Plone ZODB Python 3 migration docs <https://docs.plone.org/manage/upgrading/version_specific_migration/upgrade_zodb_to_python3.html>`_.\n\n\nQuick usage\n-----------\n\nIn a simplified ``buildout.cfg``::\n\n    [buildout]\n    parts =\n        instance\n        zodbupdate\n\n    [instance]\n    recipe = plone.recipe.zope2instance\n    eggs =\n        Plone\n        zodbverify\n\n    [zodbupdate]\n    recipe = zc.recipe.egg\n    scripts = zodbupdate\n    eggs =\n        zodbupdate\n        zest.zodbupdate\n        ${instance:eggs}\n\nRun ``bin/buildout`` and then ``bin/zodbupdate -f var/filestorage/Data.fs``.\n\n\nUse case and process\n--------------------\n\nYou want to migrate your Plone 5.2 database from Python 2.7 to Python 3.\nYou use the zodbverify and zodbupdate tools for this.\nWhen you first run ``bin/zodbverify`` or ``bin/instance zodbverify``, you may see warnings and exceptions.\nIt may warn about problems that zodbupdate will fix.\nSo the idea is now:\n\n1. First with Python 2.7, run ``bin/zodbupdate -f var/filestorage/Data.fs``\n   So *no* python3 convert stuff!\n   This will detect and apply several explicit and implicit rename rules.\n\n2. Then run ``bin/instance zodbverify``.\n   If this still gives warnings or exceptions,\n   you may need to define more rules and apply them with zodbupdate.\n\n3. When all is well, on Python 3 run::\n\n     bin/zodbupdate --convert-py3 --file=var/filestorage/Data.fs --encoding utf8\n\n4. For good measure, on Python 3 run ``bin/instance zodbverify``.\n\nWhen this works fine on a copy of your production database,\nyou could choose to safe some downtime and only do step 3 on your production database.\nBut please check this process again on a copy of your database.\n\n\nRename rules\n------------\n\nzodbverify may give warnings and exceptions like these::\n\n    Warning: Missing factory for Products.ResourceRegistries.interfaces.settings IResourceRegistriesSettings\n    Warning: Missing factory for App.interfaces IPersistentExtra\n    Warning: Missing factory for App.interfaces IUndoSupport\n    ...\n    Found X records that could not be loaded.\n    Exceptions and how often they happened:\n    ImportError: No module named ResourceRegistries.interfaces.settings: 8\n    AttributeError: 'module' object has no attribute 'IPersistentExtra': 4508\n\nFor each, you need to check if it can be safely replaced by something else,\nor if this points to a real problem: maybe a previously installed add-on is missing.\n\nIn this case, these interfaces seem no longer needed.\nEasiest is to replace them with a basic Interface.\nMaybe there are better ways to clean these up, but so far so good.\n\nYou fix these with renames in an entrypoint using zodbupdate.\nSee https://github.com/zopefoundation/zodbupdate#pre-defined-rename-rules\nThe current package defines such an entrypoint.\n\nHere is the rename dictionary from the `master branch <https://github.com/zestsoftware/zest.zodbupdate/blob/master/src/zest/zodbupdate/renames.py>`_.\nThe warnings and exceptions mentioned above are handled here.\nEach version of this package may have different contents.\n\nNote that I have seen several warnings that are not handled but that seem innocent.\nI choose to ignore them.\nThese are some warnings because of a missing ``webdav`` (removed in Zope 4.0, reintroduced in 4.3)::\n\n    Warning: Missing factory for webdav.interfaces IDAVResource\n    Warning: Missing factory for webdav.interfaces IFTPAccess\n    Warning: Missing factory for webdav.interfaces IDAVCollection\n\n\nDynamic dexterity schemas\n-------------------------\n\nA special case that ``bin/zodbupdate`` and ``bin/zodbverify`` may bump into, is::\n\n    AttributeError: Cannot find dynamic object factory for module plone.dexterity.schema.generated: 58\n    Warning: Missing factory for plone.dexterity.schema.generated Plone_0_Image\n    Warning: Missing factory for plone.dexterity.schema.generated Plone_0_Document\n    Warning: Missing factory for plone.dexterity.schema.generated Site2_0_News_1_Item\n    Warning: Missing factory for plone.dexterity.schema.generated Site3_0_Document\n\nThis is because no zcml is loaded by these scripts.\nSo this utility from ``plone.dexterity/configure.zcml`` is not registered::\n\n    <utility\n        factory=\".schema.SchemaModuleFactory\"\n        name=\"plone.dexterity.schema.generated\"\n        />\n\nThis utility implements ``plone.alterego.interfaces.IDynamicObjectFactory``.\nThis is responsible for generating schemas on the fly.\nSo we register this utility in Python code.\n\nNote that in normal use (``bin/instance``) this would result in a double registration,\nbut the second one is simply ignored by zope.interface, because it is the same.\n\nAlso, when you have zodbverify in the instance eggs and you call ``bin/instance zodbverify``,\nyou will not get this error, because then zcml is loaded, and no special handling is needed.\n\n\nPackage structure\n-----------------\n\n- This package only has an ``__init__.py`` file.\n- It has the rename dictionary pointed to by the entrypoint in our ``setup.cfg``.\n- It is only loaded when running ``bin/zodbupdate``, because this is the only code that looks for the entrypoint.\n- As a side effect, when the entrypoint is loaded we also register the dexterity utility when available.\n  This code is executed simply because it also is in the ``__init__.py`` file.\n\nChangelog\n=========\n\n\n1.0.0b2 (2020-03-25)\n--------------------\n\n- Add renames for a few webdav interfaces.\n  In Zope 4.3 webdav will return, but until then they give real errors for zodbverify on Python 3.\n  [maurits]\n\n\n1.0.0b1 (2020-03-03)\n--------------------\n\n- Initial release.  [maurits]\n\n\n", "description_content_type": "", "docs_url": null, "download_url": "", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "https://github.com/zestsoftware/zest.zodbupdate", "keywords": "Zope,Plone,ZODB", "license": "ZPL 2.1", "maintainer": "", "maintainer_email": "", "name": "zest.zodbupdate", "package_url": "https://pypi.org/project/zest.zodbupdate/", "platform": "", "project_url": "https://pypi.org/project/zest.zodbupdate/", "project_urls": {"Homepage": "https://github.com/zestsoftware/zest.zodbupdate"}, "release_url": "https://pypi.org/project/zest.zodbupdate/1.0.0b2/", "requires_dist": ["setuptools", "zodbupdate"], "requires_python": "", "summary": "zodbupdate rename rules by Zest", "version": "1.0.0b2", "yanked": false, "html_description": "<div class=\"project-description\">\n            <div id=\"zest-zodbupdate\">\n<h2>zest.zodbupdate</h2>\n<p>zodbupdate rename dictionary and dexterity patch for Plone 5.2 projects.</p>\n<p>See <a href=\"https://community.plone.org/t/zodbverify-porting-plone-with-zopedb-to-python3/8806/13\" rel=\"nofollow\">post on community.plone.org</a>.\nAnd the <a href=\"https://docs.plone.org/manage/upgrading/version_specific_migration/upgrade_zodb_to_python3.html\" rel=\"nofollow\">Plone ZODB Python 3 migration docs</a>.</p>\n<div id=\"quick-usage\">\n<h3>Quick usage</h3>\n<p>In a simplified <tt>buildout.cfg</tt>:</p>\n<pre>[buildout]\nparts =\n    instance\n    zodbupdate\n\n[instance]\nrecipe = plone.recipe.zope2instance\neggs =\n    Plone\n    zodbverify\n\n[zodbupdate]\nrecipe = zc.recipe.egg\nscripts = zodbupdate\neggs =\n    zodbupdate\n    zest.zodbupdate\n    ${instance:eggs}\n</pre>\n<p>Run <tt>bin/buildout</tt> and then <tt>bin/zodbupdate <span class=\"pre\">-f</span> var/filestorage/Data.fs</tt>.</p>\n</div>\n<div id=\"use-case-and-process\">\n<h3>Use case and process</h3>\n<p>You want to migrate your Plone 5.2 database from Python 2.7 to Python 3.\nYou use the zodbverify and zodbupdate tools for this.\nWhen you first run <tt>bin/zodbverify</tt> or <tt>bin/instance zodbverify</tt>, you may see warnings and exceptions.\nIt may warn about problems that zodbupdate will fix.\nSo the idea is now:</p>\n<ol>\n<li><p>First with Python 2.7, run <tt>bin/zodbupdate <span class=\"pre\">-f</span> var/filestorage/Data.fs</tt>\nSo <em>no</em> python3 convert stuff!\nThis will detect and apply several explicit and implicit rename rules.</p>\n</li>\n<li><p>Then run <tt>bin/instance zodbverify</tt>.\nIf this still gives warnings or exceptions,\nyou may need to define more rules and apply them with zodbupdate.</p>\n</li>\n<li><p>When all is well, on Python 3 run:</p>\n<pre>bin/zodbupdate --convert-py3 --file=var/filestorage/Data.fs --encoding utf8\n</pre>\n</li>\n<li><p>For good measure, on Python 3 run <tt>bin/instance zodbverify</tt>.</p>\n</li>\n</ol>\n<p>When this works fine on a copy of your production database,\nyou could choose to safe some downtime and only do step 3 on your production database.\nBut please check this process again on a copy of your database.</p>\n</div>\n<div id=\"rename-rules\">\n<h3>Rename rules</h3>\n<p>zodbverify may give warnings and exceptions like these:</p>\n<pre>Warning: Missing factory for Products.ResourceRegistries.interfaces.settings IResourceRegistriesSettings\nWarning: Missing factory for App.interfaces IPersistentExtra\nWarning: Missing factory for App.interfaces IUndoSupport\n...\nFound X records that could not be loaded.\nExceptions and how often they happened:\nImportError: No module named ResourceRegistries.interfaces.settings: 8\nAttributeError: 'module' object has no attribute 'IPersistentExtra': 4508\n</pre>\n<p>For each, you need to check if it can be safely replaced by something else,\nor if this points to a real problem: maybe a previously installed add-on is missing.</p>\n<p>In this case, these interfaces seem no longer needed.\nEasiest is to replace them with a basic Interface.\nMaybe there are better ways to clean these up, but so far so good.</p>\n<p>You fix these with renames in an entrypoint using zodbupdate.\nSee <a href=\"https://github.com/zopefoundation/zodbupdate#pre-defined-rename-rules\" rel=\"nofollow\">https://github.com/zopefoundation/zodbupdate#pre-defined-rename-rules</a>\nThe current package defines such an entrypoint.</p>\n<p>Here is the rename dictionary from the <a href=\"https://github.com/zestsoftware/zest.zodbupdate/blob/master/src/zest/zodbupdate/renames.py\" rel=\"nofollow\">master branch</a>.\nThe warnings and exceptions mentioned above are handled here.\nEach version of this package may have different contents.</p>\n<p>Note that I have seen several warnings that are not handled but that seem innocent.\nI choose to ignore them.\nThese are some warnings because of a missing <tt>webdav</tt> (removed in Zope 4.0, reintroduced in 4.3):</p>\n<pre>Warning: Missing factory for webdav.interfaces IDAVResource\nWarning: Missing factory for webdav.interfaces IFTPAccess\nWarning: Missing factory for webdav.interfaces IDAVCollection\n</pre>\n</div>\n<div id=\"dynamic-dexterity-schemas\">\n<h3>Dynamic dexterity schemas</h3>\n<p>A special case that <tt>bin/zodbupdate</tt> and <tt>bin/zodbverify</tt> may bump into, is:</p>\n<pre>AttributeError: Cannot find dynamic object factory for module plone.dexterity.schema.generated: 58\nWarning: Missing factory for plone.dexterity.schema.generated Plone_0_Image\nWarning: Missing factory for plone.dexterity.schema.generated Plone_0_Document\nWarning: Missing factory for plone.dexterity.schema.generated Site2_0_News_1_Item\nWarning: Missing factory for plone.dexterity.schema.generated Site3_0_Document\n</pre>\n<p>This is because no zcml is loaded by these scripts.\nSo this utility from <tt>plone.dexterity/configure.zcml</tt> is not registered:</p>\n<pre>&lt;utility\n    factory=\".schema.SchemaModuleFactory\"\n    name=\"plone.dexterity.schema.generated\"\n    /&gt;\n</pre>\n<p>This utility implements <tt>plone.alterego.interfaces.IDynamicObjectFactory</tt>.\nThis is responsible for generating schemas on the fly.\nSo we register this utility in Python code.</p>\n<p>Note that in normal use (<tt>bin/instance</tt>) this would result in a double registration,\nbut the second one is simply ignored by zope.interface, because it is the same.</p>\n<p>Also, when you have zodbverify in the instance eggs and you call <tt>bin/instance zodbverify</tt>,\nyou will not get this error, because then zcml is loaded, and no special handling is needed.</p>\n</div>\n<div id=\"package-structure\">\n<h3>Package structure</h3>\n<ul>\n<li>This package only has an <tt>__init__.py</tt> file.</li>\n<li>It has the rename dictionary pointed to by the entrypoint in our <tt>setup.cfg</tt>.</li>\n<li>It is only loaded when running <tt>bin/zodbupdate</tt>, because this is the only code that looks for the entrypoint.</li>\n<li>As a side effect, when the entrypoint is loaded we also register the dexterity utility when available.\nThis code is executed simply because it also is in the <tt>__init__.py</tt> file.</li>\n</ul>\n</div>\n</div>\n<div id=\"changelog\">\n<h2>Changelog</h2>\n<div id=\"b2-2020-03-25\">\n<h3>1.0.0b2 (2020-03-25)</h3>\n<ul>\n<li>Add renames for a few webdav interfaces.\nIn Zope 4.3 webdav will return, but until then they give real errors for zodbverify on Python 3.\n[maurits]</li>\n</ul>\n</div>\n<div id=\"b1-2020-03-03\">\n<h3>1.0.0b1 (2020-03-03)</h3>\n<ul>\n<li>Initial release.  [maurits]</li>\n</ul>\n</div>\n</div>\n\n          </div>"}, "last_serial": 6882362, "releases": {"1.0.0b1": [{"comment_text": "", "digests": {"md5": "b3c6bdc1655d95cdd122404c1a563d90", "sha256": "80f86ba8b5779c9663450d8373b079e0e5acfe74d95195278e6ec97b5eb6c42e"}, "downloads": -1, "filename": "zest.zodbupdate-1.0.0b1-py2.py3-none-any.whl", "has_sig": false, "md5_digest": "b3c6bdc1655d95cdd122404c1a563d90", "packagetype": "bdist_wheel", "python_version": "py2.py3", "requires_python": null, "size": 5283, "upload_time": "2020-03-03T17:33:18", "upload_time_iso_8601": "2020-03-03T17:33:18.469058Z", "url": "https://files.pythonhosted.org/packages/1a/74/6330ade802f45fb7b4f16401a186fc05c60f7073fd02a21f8dcc6f40addc/zest.zodbupdate-1.0.0b1-py2.py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "ed0dee6d3e1770701f45518e75973eda", "sha256": "c63672cb8a86a26ce28b209870ee393304c9a2acd607e226b1a303ea35329890"}, "downloads": -1, "filename": "zest.zodbupdate-1.0.0b1.tar.gz", "has_sig": false, "md5_digest": "ed0dee6d3e1770701f45518e75973eda", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 4648, "upload_time": "2020-03-03T17:33:20", "upload_time_iso_8601": "2020-03-03T17:33:20.493874Z", "url": "https://files.pythonhosted.org/packages/8f/42/d5dc92d172bef884ab64e5eed47aa0a0fb3bfd18ee1cc2ee41506103fa15/zest.zodbupdate-1.0.0b1.tar.gz", "yanked": false}], "1.0.0b2": [{"comment_text": "", "digests": {"md5": "397af8c3b8bd14e424561e7982d16dbf", "sha256": "30432fe190d53d0ce2e4189d325c0a677dfec14e7f4dba2fc64b98e394282a6d"}, "downloads": -1, "filename": "zest.zodbupdate-1.0.0b2-py2.py3-none-any.whl", "has_sig": false, "md5_digest": "397af8c3b8bd14e424561e7982d16dbf", "packagetype": "bdist_wheel", "python_version": "py2.py3", "requires_python": null, "size": 5715, "upload_time": "2020-03-25T17:21:36", "upload_time_iso_8601": "2020-03-25T17:21:36.701398Z", "url": "https://files.pythonhosted.org/packages/0e/59/f9517b46222d89fa06ecd37f0bccca0f28dd5f7bce56bd123aac3c3cac57/zest.zodbupdate-1.0.0b2-py2.py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "2907282b894ae356bcec3d48d6fa6808", "sha256": "f1040a640a66fb7bdc4696f7bf7ec9f7310dd20ff36a08aa28b08c6fa509429b"}, "downloads": -1, "filename": "zest.zodbupdate-1.0.0b2.tar.gz", "has_sig": false, "md5_digest": "2907282b894ae356bcec3d48d6fa6808", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 5013, "upload_time": "2020-03-25T17:21:40", "upload_time_iso_8601": "2020-03-25T17:21:40.270578Z", "url": "https://files.pythonhosted.org/packages/74/a2/ca650af5f5550bdde4597010e4f1f9530191241d3c80900178113f9312fc/zest.zodbupdate-1.0.0b2.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "397af8c3b8bd14e424561e7982d16dbf", "sha256": "30432fe190d53d0ce2e4189d325c0a677dfec14e7f4dba2fc64b98e394282a6d"}, "downloads": -1, "filename": "zest.zodbupdate-1.0.0b2-py2.py3-none-any.whl", "has_sig": false, "md5_digest": "397af8c3b8bd14e424561e7982d16dbf", "packagetype": "bdist_wheel", "python_version": "py2.py3", "requires_python": null, "size": 5715, "upload_time": "2020-03-25T17:21:36", "upload_time_iso_8601": "2020-03-25T17:21:36.701398Z", "url": "https://files.pythonhosted.org/packages/0e/59/f9517b46222d89fa06ecd37f0bccca0f28dd5f7bce56bd123aac3c3cac57/zest.zodbupdate-1.0.0b2-py2.py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "2907282b894ae356bcec3d48d6fa6808", "sha256": "f1040a640a66fb7bdc4696f7bf7ec9f7310dd20ff36a08aa28b08c6fa509429b"}, "downloads": -1, "filename": "zest.zodbupdate-1.0.0b2.tar.gz", "has_sig": false, "md5_digest": "2907282b894ae356bcec3d48d6fa6808", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 5013, "upload_time": "2020-03-25T17:21:40", "upload_time_iso_8601": "2020-03-25T17:21:40.270578Z", "url": "https://files.pythonhosted.org/packages/74/a2/ca650af5f5550bdde4597010e4f1f9530191241d3c80900178113f9312fc/zest.zodbupdate-1.0.0b2.tar.gz", "yanked": false}], "timestamp": "Fri May  8 03:17:22 2020"}